workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
#      android_signing:
#        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.dicoding.ditonton"
        GOOGLE_PLAY_TRACK: alpha
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: cgg watchlist module
        script: |
          cd watchlist
          make cgg
      - name: cgg search module
        script: |
          cd search
          make cgg
      - name: cgg tv_series module
        script: |
          cd tv_series
          make cgg
      - name: cgg movie module
        script: |
          cd movie
          make cgg
      - name: cgg core module
        script: |
          cd core
          make cgg
      - name: cgg host app
        script: |
          make cgg
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - gitarringsek@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true