// Mocks generated by Mockito 5.4.6 from annotations
// in core/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i27;
import 'dart:typed_data' as _i28;

import 'package:core/data/datasources/db/database_helper.dart' as _i16;
import 'package:core/data/datasources/movie/movie_local_data_source.dart'
    as _i14;
import 'package:core/data/datasources/movie/movie_remote_data_source.dart'
    as _i12;
import 'package:core/data/datasources/tv/tv_series_local_data_source.dart'
    as _i21;
import 'package:core/data/datasources/tv/tv_series_remote_data_source.dart'
    as _i19;
import 'package:core/data/datasources/watchlist_local_data_source.dart' as _i22;
import 'package:core/data/models/movie/movie_detail_model.dart' as _i3;
import 'package:core/data/models/movie/movie_model.dart' as _i13;
import 'package:core/data/models/tv/tv_series_detail_model.dart' as _i4;
import 'package:core/data/models/tv/tv_series_model.dart' as _i20;
import 'package:core/data/models/watchlist_model.dart' as _i15;
import 'package:core/domain/entities/movie/movie.dart' as _i9;
import 'package:core/domain/entities/movie/movie_detail.dart' as _i10;
import 'package:core/domain/entities/tv/tv_series.dart' as _i25;
import 'package:core/domain/entities/tv/tv_series_detail.dart' as _i26;
import 'package:core/domain/entities/watchlist.dart' as _i11;
import 'package:core/domain/repositories/movie_repository.dart' as _i6;
import 'package:core/domain/repositories/tv_series_repository.dart' as _i24;
import 'package:core/utils/failure.dart' as _i8;
import 'package:core/utils/network_info.dart' as _i18;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;
import 'package:sqflite/sqflite.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailResponse_2 extends _i1.SmartFake
    implements _i4.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i6.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getNowPlayingMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getPopularMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getTopRatedMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetail>>.value(
                  _FakeEither_0<_i8.Failure, _i10.MovieDetail>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetail>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getMovieRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getMovieRecommendations, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#searchMovies, [query]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveWatchlist(
    _i10.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [movie]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeWatchlist(
    _i10.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i11.Watchlist>>>
  getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i11.Watchlist>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i11.Watchlist>>(
                    this,
                    Invocation.method(#getWatchlistMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i11.Watchlist>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i12.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i13.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i7.Future<List<_i13.MovieModel>>.value(
              <_i13.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i13.MovieModel>>);

  @override
  _i7.Future<List<_i13.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i7.Future<List<_i13.MovieModel>>.value(
              <_i13.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i13.MovieModel>>);

  @override
  _i7.Future<List<_i13.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i7.Future<List<_i13.MovieModel>>.value(
              <_i13.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i13.MovieModel>>);

  @override
  _i7.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i7.Future<_i3.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_1(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.MovieDetailResponse>);

  @override
  _i7.Future<List<_i13.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i7.Future<List<_i13.MovieModel>>.value(
              <_i13.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i13.MovieModel>>);

  @override
  _i7.Future<List<_i13.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i7.Future<List<_i13.MovieModel>>.value(
              <_i13.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i13.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i14.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> cacheNowPlayingMovies(List<_i15.WatchlistModel>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheNowPlayingMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i15.WatchlistModel>> getCachedNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedNowPlayingMovies, []),
            returnValue: _i7.Future<List<_i15.WatchlistModel>>.value(
              <_i15.WatchlistModel>[],
            ),
          )
          as _i7.Future<List<_i15.WatchlistModel>>);

  @override
  _i7.Future<List<_i15.WatchlistModel>> getCachedAiringTodayTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAiringTodayTvSeries, []),
            returnValue: _i7.Future<List<_i15.WatchlistModel>>.value(
              <_i15.WatchlistModel>[],
            ),
          )
          as _i7.Future<List<_i15.WatchlistModel>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i16.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i17.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i17.Database?>.value(),
          )
          as _i7.Future<_i17.Database?>);

  @override
  _i7.Future<int> insertWatchlist(_i15.WatchlistModel? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlist(_i15.WatchlistModel? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getWatchlistItemById(
    int? id,
    String? contentType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistItemById, [id, contentType]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> insertCacheTransaction(
    List<_i15.WatchlistModel>? movies,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransaction, [movies, category]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheMovies, [category]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i18.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [TVSereisRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSereisRemoteDataSource extends _i1.Mock
    implements _i19.TVSereisRemoteDataSource {
  MockTVSereisRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i20.TvSeriesModel>> getAiringTodayTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getAiringTodayTvSeries, []),
            returnValue: _i7.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i20.TvSeriesModel>>);

  @override
  _i7.Future<List<_i20.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i7.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i20.TvSeriesModel>>);

  @override
  _i7.Future<List<_i20.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i7.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i20.TvSeriesModel>>);

  @override
  _i7.Future<_i4.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i7.Future<_i4.TvSeriesDetailResponse>.value(
              _FakeTvSeriesDetailResponse_2(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.TvSeriesDetailResponse>);

  @override
  _i7.Future<List<_i20.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue: _i7.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i20.TvSeriesModel>>);

  @override
  _i7.Future<List<_i20.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i7.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i20.TvSeriesModel>>);
}

/// A class which mocks [TVSereisLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSereisLocalDataSource extends _i1.Mock
    implements _i21.TVSereisLocalDataSource {
  MockTVSereisLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> cacheAiringTodayTvSeries(
    List<_i15.WatchlistModel>? movies,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheAiringTodayTvSeries, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i15.WatchlistModel>> getCachedAiringTodayTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAiringTodayTvSeries, []),
            returnValue: _i7.Future<List<_i15.WatchlistModel>>.value(
              <_i15.WatchlistModel>[],
            ),
          )
          as _i7.Future<List<_i15.WatchlistModel>>);
}

/// A class which mocks [WatchlistLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLocalDataSource extends _i1.Mock
    implements _i22.WatchlistLocalDataSource {
  MockWatchlistLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i15.WatchlistModel?> getWatchlistItemById(
    int? id,
    String? contentType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistItemById, [id, contentType]),
            returnValue: _i7.Future<_i15.WatchlistModel?>.value(),
          )
          as _i7.Future<_i15.WatchlistModel?>);

  @override
  _i7.Future<String> insertWatchlist(_i15.WatchlistModel? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i7.Future<String>.value(
              _i23.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> removeWatchlist(_i15.WatchlistModel? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i7.Future<String>.value(
              _i23.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<List<_i15.WatchlistModel>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i7.Future<List<_i15.WatchlistModel>>.value(
              <_i15.WatchlistModel>[],
            ),
          )
          as _i7.Future<List<_i15.WatchlistModel>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i24.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>
  getAiringTodayTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getAiringTodayTvSeries, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i25.TVSeries>>(
                    this,
                    Invocation.method(#getAiringTodayTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>
  getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i25.TVSeries>>(
                    this,
                    Invocation.method(#getPopularTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>
  getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i25.TVSeries>>(
                    this,
                    Invocation.method(#getTopRatedTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i26.TvSeriesDetail>> getTvDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, _i26.TvSeriesDetail>>.value(
                  _FakeEither_0<_i8.Failure, _i26.TvSeriesDetail>(
                    this,
                    Invocation.method(#getTvDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, _i26.TvSeriesDetail>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>
  getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i25.TVSeries>>(
                    this,
                    Invocation.method(#getTvSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveWatchlist(
    _i26.TvSeriesDetail? tvSeriesDetail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tvSeriesDetail]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tvSeriesDetail]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeWatchlist(
    _i26.TvSeriesDetail? tvSeriesDetail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeriesDetail]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeriesDetail]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i25.TVSeries>>(
                    this,
                    Invocation.method(#searchTvSeries, [query]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i25.TVSeries>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i7.Future<String>.value(
              _i23.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i28.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i7.Future<_i28.Uint8List>.value(_i28.Uint8List(0)),
          )
          as _i7.Future<_i28.Uint8List>);

  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i7.Future<_i5.StreamedResponse>.value(
              _FakeStreamedResponse_4(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
